[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read", path = "lib/foundry-chainlink-toolkit/out" }]

remappings = [
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@openzeppelin/=lib/openzeppelin-contracts-upgradeable/"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

